# Generated by Django 4.1.3 on 2022-11-07 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.CharField(default='nobody', max_length=200),
        ),
    ]
