# Generated by Django 4.1.3 on 2022-12-06 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grouping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='persons', to='grouping.group'),
        ),
    ]
