# Generated by Django 4.1.3 on 2022-12-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grouping', '0003_alter_person_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='persons', to='grouping.group'),
        ),
    ]
